Fused_ops UT: Fix adamw_ut
The following error was due to the import order of
habana frameworks/plugin

Variable._execution_engine.run_backward(  # Calls into
the C++ engine to run the backward pass
RuntimeError: 0 <= device.index() && device.index()
< static_cast<c10::DeviceIndex>(device_ready_queues_.size())
INTERNAL ASSERT FAILED at "../torch/csrc/autograd/engine.cpp":1191,
please report a bug to PyTorch.

Change-Id: I3c3e77fdefec4f4d59baa3b5f9d8d0b853349350
Signed-off-by: Internal Developer <internal-developer@intel.com>