Fix compilation error in debug mode
With spdlog inclusion in commit "b29fb058  Add Statistics
module", build fails due to:

/home/gsingh/trees/npu-stack/3rd-parties/spdlog/include/spdlog/fmt/bundled/format.h:1793:17:
error: comparison of integer expressions of different signedness: ‘long
long unsigned int’ and ‘int’ [-Werror=sign-compare]

Suppress this error by disabling sign-compare warnings.

Change-Id: I74e1e2aa41604c46299605692bd60739008107f9