fix for a test due to changed behaviour of foreach ops
Fixing error "AttributeError: 'list' object has no attribute 'cpu'"

Since PT2.3 inplace foreach ops return List[Tensor] instead of
None:
https://github.com/pytorch/pytorch/pull/118622

Change-Id: I2215753030a0ff6c9c60fc1abb6b29c1b292158f