Pickle weight sharing's wrapped_to
The `change_device_placement` closure was not picklable because it was a
local object. With PT 2.0 we got the following error:

AttributeError: Can't pickle local object 'wrapped_to.<locals>.
add_device_placement_workaround.<locals>.change_device_placement

To enable pickling, it's changed to a top-level function object.

Change-Id: Id504d81893d869b84339a484b21ff082747ca3f2